shell fish
# FONT
font_family      JetBrains Mono Nerd Font Mono
font_size 12.0
# Scroll back buffer and pager
scrollback_lines 10000
scrollback_pager nvim -u NONE
  \ -c "set termguicolors laststatus=0 clipboard+=unnamedplus nomodifiable"
  \ -c "set ignorecase smartcase"
  \ -c "map <silent> q :qa!<CR>"
  \ -c "lua for _, k in ipairs({'i', 'a', 'I', 'A', 'o', 'O', 's', 'S', 'R'}) do
  \   vim.keymap.set('n', k, '<Nop>')
  \ end"
  \ -c "autocmd VimEnter * lua
  \ s = vim.api.nvim_buf_get_lines(0, 0, -1, false)
  \ b = vim.api.nvim_create_buf(false, true)
  \ c = vim.api.nvim_open_term(b, {})
  \ vim.api.nvim_chan_send(c, table.concat(s, string.char(10)))
  \ vim.api.nvim_set_current_buf(b)
  \ vim.api.nvim_buf_delete(1, {force = true})
  \ vim.defer_fn(function()
  \   local row = math.max(1, INPUT_LINE_NUMBER + CURSOR_LINE - 1)
  \   local col = CURSOR_COLUMN
  \   vim.cmd('normal! ' .. row .. 'G' .. col .. '|')
  \ end, 10)"
  \ -

# Window margin
window_margin_width 3
# Disable checking updates
update_check_interval 0
# Jumpy cursor trail
cursor_trail 3
cursor_trail_decay 0.02 0.1
cursor_shape beam
hide_window_decorations yes
